<!DOCTYPE html>
<html>
<head>
  <title>Amigo</title>
  <link rel="stylesheet" href="/css/main.css">
</head>

<body>
  <div class="general">
    <h1 class="nombreFormulario">Amigo</h1>

    <div class="formulario">
      <form action="/amigo" method="post" >
        
      <div class="element-container container-idPerfil">
          <label for="idPerfil" class="label label-idPerfil" >idPerfil:</label>
          <input type="text" id="idPerfil" name="idPerfil">
        </div>   

        <div class="element-container container-idAmigo">
          <label for="idAmigo" class="label label-idAmigo" >idAmigo:</label>
          <input type="text" id="idAmigo" name="idAmigo">
        </div>           
        
        <input type="submit" value="Submit" class="submit" id="submit">
      </form>
    </div>
  </div>
</body>

</html>
</Html>
