<!DOCTYPE html>
<html>
<head>
  <title>pais</title>
  <link rel="stylesheet" href="/css/main.css">
</head>

<body>
  <div class="general">
    <h1 class="nombreFormulario">Pais</h1>

    <div class="formulario">
      <form action="/pais" method="post" >
        
        <div class="element-container container-name">
          <label for="name" class="label label-name" >nombre:</label>
          <input type="text" id="name" name="name">
        </div>        
        
        <input type="submit" value="Submit" class="submit" id="submit">
      </form>
    </div>
  </div>
</body>

</html>
</Html>

